// Influencer Tags - Complete list of available tags for influencer profiles
export const INFLUENCER_TAGS = [
  'LGBTQ+',
  'Fashion',
  'Beauty',
  'Lifestyle',
  'Fitness and Wellness',
  'Food',
  'Travel',
  'Tech',
  'Gaming',
  'Finance',
  'Education & Learning',
  'Hobbies & Crafts',
  'Automotive',
  'Career & Professional Development',
  'Literature',
  'Culture',
  'Comedy',
  'Sports',
  'Actor',
  'Dance/Choreography',
  'Singer',
  'Photography',
  'Relationship',
  'Political',
  'Yoga',
  'Meditation',
  'Mental Health',
  'Glamour',
  'Vines',
  'Startup',
  'Entrepreneur',
  'Architecture',
  'Memes',
  'Design',
  'Social Justice',
  'Adventure',
  'Motorsports',
  'Crypto',
  'Stock Market',
  'Environment',
  'Artificial Intelligence',
  'Movies',
  'OTT',
  'Television',
] as const;

